// C7-FX-12: for every fixture, its construction assumption and the distance
// from each displayed value to the nearest tie at its displayed precision —
// the figure itself. `npm run fixture-record` writes docs/fixture-record.md.
import { determine } from '../src/engine/determine.js';
import { tieDistance, gridDistance } from '../src/engine/numfmt.js';
import { ENGINE_VERSION } from '../src/engine/version.js';
import { FIXTURES } from './fixtures.js';

const out = [`# C7-FX-12 — fixture record\n\nEngine ${ENGINE_VERSION}. Generated by \`npm run fixture-record\`. For each displayed value: the value shown, and the exact distance from its unrounded value (in the displayed unit) to the nearest decimal tie at its displayed precision. An entered diluent is displayed as entered and has no tie. A directed bound (an \"at most\" concentration rounded up, an \"at least\" final volume rounded down — spec/decision-2026-09-28-directed-rounding.md) is critical at the grid points, so its distance is to the nearest grid point.\n\n**The molar path is not discharged.** The C7-FX-09 rows and the C7-IV-05 cases use synthetic C1 objects built to C1's serialise.ts shape, because C1 emits no transport envelope yet. They show the engine applies the §8 table as written; they do not discharge acceptance 11 or C7-FX-09, which wait on real C1 v0.6 output run through every row.\n`];
for (const fx of FIXTURES) {
  const r = determine(fx.input);
  if (r.status === 'rejected') {
    out.push(`## ${fx.id} — ${fx.name}\n\n${fx.construction}\n\nRejected: ${r.rejections.map((x) => `${x.code} — ${x.message}`).join(' ')}\n\nNo value is displayed, so no tie distance applies.\n`);
    continue;
  }
  const u = r.volumes.unit;
  const rows = [];
  const add = (name, shown, unrounded, n, directed = false) => rows.push(`| ${name}${directed ? ' — directed bound' : ''} | \`${shown}\` | ${unrounded === null ? '— (entered)' : `\`${directed ? gridDistance(unrounded, n) : tieDistance(unrounded, n)}\`${directed ? ' (to the nearest grid point)' : ''}`} |`);
  add(`diluent Vd′ (${u})`, r.volumes.diluent.display, r.volumes.diluent.role === 'entered' ? null : r.volumes.diluent.unroundedBeforeDisplay, 3);
  add(`final Fa (${u})`, r.volumes.final.display, r.volumes.final.unrounded, 3, r.volumes.final.rounding === 'down');
  if (r.displacement.computed) add(`D (${u})`, r.displacement.computed.D.display, r.displacement.computed.D.unrounded, 3);
  if (r.displacement.Dmin) add(`Dmin (${u})`, r.displacement.Dmin.display, r.displacement.Dmin.unrounded, 3);
  add(`concentration (${r.concentration.reported.unit})`, r.concentration.reported.display, r.concentration.reported.unrounded, 6, r.concentration.reported.rounding === 'up');
  if (r.displacement.computed) add('f (fraction)', r.displacement.computed.f.display, r.displacement.computed.f.unrounded, 3);
  if (r.displacement.Dmin) add('fmin (fraction)', r.displacement.Dmin.fmin.display, r.displacement.Dmin.fmin.unrounded, 3);
  out.push(`## ${fx.id} — ${fx.name}\n\n${fx.construction}\n\nFlags raised: ${r.flags.map((f) => f.code).join(', ') || 'none'}.\n\n| Displayed value | Shown | Distance to nearest tie |\n|---|---|---|\n${rows.join('\n')}\n`);
}
console.log(out.join('\n'));
