// Writes the C7-IV-02 demonstration record: each measure's clean discrepancy
// and the discrepancy under each inserted defect. `npm run mutation-record`.
import { TOLERANCES } from '../src/engine/constants.js';
import { ENGINE_VERSION } from '../src/engine/version.js';
import { roundTrip, unitNormalisation, molarRoute, DEFECTS } from './invariance.js';
import { C1 } from './c1-fixture.js';

const rows = [
  ['C7-IV-01 round trip', 'roundTrip', (o) => roundTrip(o), TOLERANCES.roundTrip],
  ['C7-IV-04 unit normalisation', 'unitNormalisation', (o) => unitNormalisation(o), TOLERANCES.unitNormalisation],
  ['C7-IV-05 molar route', 'molarRoute', (o) => molarRoute(o, C1), TOLERANCES.unitNormalisation],
];
const e = (x) => (x === Infinity ? '∞' : x.toExponential(3));
console.log(`# C7-IV-02 — invariance tests shown capable of failing\n\nEngine ${ENGINE_VERSION}. Generated by \`npm run mutation-record\` (tests/mutation-record.mjs). Every figure is the worst relative discrepancy on unrounded structured values over the cases in tests/invariance.js. ∞ means the defect drove at least one case to a rejection or a non-representable value — a failure of the invariance as surely as a disagreement.\n`);
console.log('| Measure | Tolerance | Clean | Clamp | Floor | Nudge | Detected |\n|---|---|---|---|---|---|---|');
for (const [name, key, m, tol] of rows) {
  const clean = m({});
  const d = Object.fromEntries(Object.entries(DEFECTS[key]).map(([k, fn]) => [k, m({ _mutate: fn })]));
  const caught = Object.values(d).every((x) => x > 1e-12 && x > 1000 * clean && (tol === null || x > tol));
  console.log(`| ${name} | ${tol === null ? 'open' : e(tol)} | ${e(clean)} | ${e(d.clamp)} | ${e(d.floor)} | ${e(d.nudge)} | ${caught ? 'yes' : 'NO'} |`);
}
console.log('\nThe defects are inserted through the engine\'s test-only `_mutate` seam (src/engine/determine.js): the clamp and the floor at a stage on each measure\'s path, the nudge a 1 × 10⁻⁹ relative change. Each is detected: its discrepancy exceeds the clean discrepancy by more than three orders of magnitude.\n\n**Pending:** "each inserted defect exceeds the derived tolerance" (C7-IV-02) cannot be shown until outstanding item 3 derives the tolerances. When the constants in src/engine/constants.js are filled, the same tests check it, and this record is regenerated. The 1 × 10⁻⁹ nudge is chosen to sit far above any plausible floating-point bound for a handful of correctly rounded operations (~10⁻¹⁵); if the derived bound is looser than 10⁻⁹, the nudge must be enlarged to match.');
